/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Centros;
import ejerciciofase2.EjercicioFase2;
import javax.swing.JOptionPane;
import Excepciones.*;

public class NuevoCentro extends javax.swing.JFrame {

    public static Centros ce;
    
    public NuevoCentro() {
        initComponents();
        
        ce = null;
        
        if(EjercicioFase2.getNm() == true){
            tfNombre.setEnabled(true);
            tfCalle.setEnabled(true);
            tfNumero.setEnabled(true);
            tfCp.setEnabled(true);
            tfCiudad.setEnabled(true);
            tfProvincia.setEnabled(true);
            tfTelefono.setEnabled(true);
            bGuardar.setEnabled(true);
            
            ce = EjercicioFase2.mostrarCentro();
            
            tfNombre.setText(ce.getNombre());
            tfCalle.setText(ce.getCalle());
            tfNumero.setText(ce.getNumero());
            tfCp.setText(ce.getCp());
            tfCiudad.setText(ce.getCiudad());
            tfProvincia.setText(ce.getProvincia());
            tfTelefono.setText(ce.getTelefono());
        }
        else
        {
            tfNombre.setEnabled(true);
            tfCalle.setEnabled(false);
            tfNumero.setEnabled(false);
            tfCp.setEnabled(false);
            tfCiudad.setEnabled(false);
            tfProvincia.setEnabled(false);
            tfTelefono.setEnabled(false);
            bGuardar.setEnabled(false);
            
            tfNombre.setText("");
            tfCalle.setText("");
            tfNumero.setText("");
            tfCp.setText("");
            tfCiudad.setText("");
            tfProvincia.setText("");
            tfTelefono.setText("");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCalle = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfCiudad = new javax.swing.JTextField();
        tfProvincia = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tfCp = new javax.swing.JFormattedTextField();
        tfTelefono = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("NUEVO CENTRO");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("CALLE:");

        jLabel4.setText("NUMERO:");

        jLabel5.setText("CODIGO POSTAL:");

        jLabel6.setText("CIUDAD:");

        jLabel7.setText("PROVINCIA:");

        jLabel8.setText("TELEFONO:");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfCalle.setEnabled(false);
        tfCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCalleActionPerformed(evt);
            }
        });

        tfNumero.setEnabled(false);
        tfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroActionPerformed(evt);
            }
        });

        tfCiudad.setEnabled(false);
        tfCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCiudadActionPerformed(evt);
            }
        });

        tfProvincia.setEnabled(false);
        tfProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProvinciaActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.setEnabled(false);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        try {
            tfCp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCp.setEnabled(false);
        tfCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpActionPerformed(evt);
            }
        });

        try {
            tfTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefono.setEnabled(false);
        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre)
                                    .addComponent(tfCalle)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfProvincia)
                                    .addComponent(tfTelefono)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(bGuardar)
                        .addGap(71, 71, 71)
                        .addComponent(bCancelar)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bGuardar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCalleActionPerformed
        try{
            if(tfCalle.getText().isEmpty())
                throw new CampoVacio();
            else{
                tfCalle.setEnabled(false);
                tfNumero.requestFocus();
                tfNumero.setEnabled(true);
            }
        }
        catch(CampoVacio e){
            javax.swing.JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_tfCalleActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        char cancelar;
        do{
            cancelar= JOptionPane.showInputDialog(this,"¿Estas segur@ que quieres salir de esta ventana? <s/n>").toLowerCase().charAt(0);
        }
        while(cancelar!='s' && cancelar!='n');
        
        if(cancelar=='s'){
            EjercicioFase2.cerrarNc();
            EjercicioFase2.cerrarCentro();
            EjercicioFase2.crearCentro();
        }
        
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if(EjercicioFase2.getNm() == true){
            EjercicioFase2.editarCentro(tfNombre.getText(), tfCalle.getText(), tfNumero.getText(), tfCp.getText(), tfCiudad.getText(), tfProvincia.getText(), tfTelefono.getText());
            EjercicioFase2.cerrarNc();
        }
        else{
        EjercicioFase2.insertCentro(tfNombre.getText(), tfCalle.getText(), tfNumero.getText(), tfCp.getText(), tfCiudad.getText(), tfProvincia.getText(), tfTelefono.getText());
        }
        EjercicioFase2.cerrarNc();
        EjercicioFase2.cerrarCentro();
        EjercicioFase2.crearCentro();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        try{
            if(tfNombre.getText().isEmpty())
                throw new CampoVacio();
            else{
                tfNombre.setEnabled(false);
                tfCalle.requestFocus();
                tfCalle.setEnabled(true);
            }
        }
        catch(CampoVacio e){
            javax.swing.JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroActionPerformed
        try{
            if(tfNumero.getText().isEmpty())
                throw new CampoVacio();
            else{
                int n = Integer.parseInt(tfNumero.getText());
                tfNumero.setEnabled(false);
                tfCp.requestFocus();
                tfCp.setEnabled(true);
            }
        }
        catch(CampoVacio e){
            javax.swing.JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
        catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Todos los caracteres deben de ser numericos");
            tfNumero.setText("");
        }
    }//GEN-LAST:event_tfNumeroActionPerformed

    private void tfCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpActionPerformed
        if(tfCp.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "El campo no puede quedar vacio");
        else{
            tfCp.setEnabled(false);
            tfCiudad.setEnabled(true);
            tfCiudad.requestFocus();
        }
    }//GEN-LAST:event_tfCpActionPerformed

    private void tfCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCiudadActionPerformed
        try{
            if(tfCiudad.getText().isEmpty())
                throw new CampoVacio();
            else{
                tfCiudad.setEnabled(false);
                tfProvincia.requestFocus();
                tfProvincia.setEnabled(true);
            }
        }
        catch(CampoVacio e){
            javax.swing.JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_tfCiudadActionPerformed

    private void tfProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProvinciaActionPerformed
        try{
            if(tfProvincia.getText().isEmpty())
                throw new CampoVacio();
            else{
                tfProvincia.setEnabled(false);
                tfTelefono.requestFocus();
                tfTelefono.setEnabled(true);
            }
        }
        catch(CampoVacio e){
            javax.swing.JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_tfProvinciaActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        if(tfTelefono.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "El campo no puede quedar vacio");
        else{
            tfTelefono.setEnabled(false);
            bGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_tfTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCentro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfCalle;
    private javax.swing.JTextField tfCiudad;
    private javax.swing.JFormattedTextField tfCp;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfProvincia;
    private javax.swing.JFormattedTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
